#!/bin/bash
# Community (syzbot) reproducer for: WARNING in ip_rt_bug
# https://syzkaller.appspot.com/bug?id=b89b76e33d398c544f3ecb6fe9896d099a8a0a87
# Runs the autogenerated syzkaller C reproducer and checks dmesg.

set -e

LOG="/mnt/shared/repro_syz_test.log"
REPRO_NAME="repro_syz"

{
    echo "=== syzbot C reproducer (WARNING in ip_rt_bug) ==="
    echo "Test time: $(date)"
    echo "Kernel: $(uname -r)"

    if [ ! -f "/mnt/shared/${REPRO_NAME}" ]; then
        echo "ERROR: reproducer binary not found: /mnt/shared/${REPRO_NAME}"
        exit 1
    fi

    cp "/mnt/shared/${REPRO_NAME}" /tmp/${REPRO_NAME}
    chmod +x /tmp/${REPRO_NAME}

    echo "Running reproducer (30s timeout)..."
    echo 0 > /proc/sys/net/ipv4/conf/all/rp_filter
    echo 0 > /proc/sys/net/ipv4/conf/default/rp_filter
    cd /tmp
    rm -rf syz-tmp
    timeout 30 /tmp/${REPRO_NAME} > /tmp/repro_syz.out 2>&1 || true
    echo "--- reproducer output (first 20 lines) ---"
    head -20 /tmp/repro_syz.out

    echo ""
    echo "=== Checking dmesg for ip_rt_bug / WARNING ==="
    if dmesg | grep -qE "ip_rt_bug|WARNING:"; then
        echo "RESULT: REPRODUCED - ip_rt_bug or WARNING in dmesg"
        dmesg | grep -E "ip_rt_bug|WARNING:" | head -10
    else
        echo "RESULT: NOT REPRODUCED - no ip_rt_bug/WARNING in dmesg"
    fi

    echo ""
    echo "=== Full dmesg tail (30 lines) ==="
    dmesg | tail -30
} | tee "$LOG"

exit 0
